FirstDemo.OA/FirstDemo.OA/Models/MyExceptionAttribute.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FirstDemo.OA.Models
{
    public class MyExceptionAttribute : HandleErrorAttribute
    {
        public static Queue<Exception> ExceptionQueue = new Queue<Exception>();
        /// <summary>
        /// 可以捕获异常数据
        /// </summary>
        /// <param name="filterContext"></param>
        public override void OnException(ExceptionContext filterContext)
        {
            base.OnException(filterContext);
            Exception ex = filterContext.Exception;
            //写入队列
            ExceptionQueue.Enqueue(ex);
            filterContext.HttpContext.Response.Redirect("/Error.html");
        }
    }
}

FirstDemo.OA/FirstDemo.OA/Controllers/BaseController.cs
using FirstDemo.OA.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FirstDemo.OA.Controllers
{
    public class BaseController : Controller
    {
        public UserInfo LoginUser { get; set; }

        /// <summary>
        /// 执行控制器中的方法前先执行此方法
        /// </summary>
        /// <param name="filterContext"></param>
        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            base.OnActionExecuting(filterContext);
            //if (Session["userInfo"] == null)
            bool isSucess = false;
            if (Request.Cookies["sessionId"] != null)
            {
                string sessionid = Request.Cookies["sessionId"].Value;
                //根据该值查memcache
                object obj = Common.MemcacheHelper.Get(sessionid);
                if (obj != null)
                {
                    UserInfo userInfo = Common.SerializeHelper.DeserializeToObject<UserInfo>(obj.ToString());
                    LoginUser = userInfo;
                    isSucess = true;
                    Common.MemcacheHelper.Set(sessionid, obj, DateTime.Now.AddMinutes(20));//模拟出滑动过期时间
                }
                //filterContext.Result = Redirect("/Login/Index");
            }
            if (!isSucess)
            {
                filterContext.Result = Redirect("/Login/Index");
            }
        }
    }
}

FirstDemo.OA/FirstDemo.OA/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FirstDemo.OA.Controllers
{
    public class HomeController : BaseController
    {
        // GET: Home
        public ActionResult Index()
        {
            ViewData["name"] = LoginUser.UName;
            return View();
        }
        public ActionResult HomePage()
        {
            return View();
        }
    }
}

FirstDemo.OA/FirstDemo.OA/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FirstDemo.OA.Controllers
{
    public class LoginController : Controller
    {
        IBLL.IUserInfoService UserInfoService = new BLL.UserInfoService();
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }
        #region 完成用户登录
        public ActionResult UserLogin()
        {
            string validateCode = Session["validateCode"] != null ? Session["validateCode"].ToString() : string.Empty;
            if (string.IsNullOrEmpty(validateCode))
            {
                return Content("no:验证码错误!!");
            }
            Session["validateCode"] = null;
            string txtCode = Request["vCode"];
            if (!validateCode.Equals(txtCode, StringComparison.InvariantCultureIgnoreCase))
            {
                return Content("no:验证码错误!!");
            }
            string userName = Request["loginCode"];
            string userPwd = Request["LoginPwd"];
            var userInfo = UserInfoService.LoadEntities(c => c.UName == userName && c.UPwd == userPwd).FirstOrDefault();//根据用户名找用户
            if (userInfo != null)
            {
                //Session["UserInfo"] = userInfo;
                //产生一个GUID值作为Memache的键  
                string sessionId = Guid.NewGuid().ToString();
                Common.MemcacheHelper.Set(sessionId, Common.SerializeHelper.SerializeToString(userInfo), DateTime.Now.AddMinutes(20));//将登陆信息存储在memcache里
                Response.Cookies["sessionId"].Value = sessionId;//将memcache的key以cookie的形式返回给浏览器
                return Content("ok:登录成功");
            }
            else
            {
                return Content("no:登录失败!!");
            }
        }
        #endregion

        #region 显示验证码

        public ActionResult ShowValidateCode()
        {
            Common.ValidateCode validateCode = new Common.ValidateCode();
            string code = validateCode.CreateValidateCode(4);//产生验证码
            Session["validateCode"] = code;
            byte[] buffer = validateCode.CreateValidateGraphic(code);//将验证码画到画布上
            return File(buffer, "image/jpeg");
        }
        #endregion
    }
}

FirstDemo.OA/FirstDemo.OA/Controllers/UserInfoController.cs
using FirstDemo.OA.Model;
using FirstDemo.OA.Model.EnumType;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FirstDemo.OA.Controllers
{
    public class UserInfoController : Controller
    {
        // GET: UserInfo
        IBLL.IUserInfoService UserInfoService = new BLL.UserInfoService();
        public ActionResult Index()
        {

            return View();
        }

        #region 获取用户信息列表

        public ActionResult GetUserInfoList()
        {
            int pageIndex = Request["page"] != null ? int.Parse(Request["page"]) : 1;
            int pageSize = Request["rows"] != null ? int.Parse(Request["rows"]) : 5;
            //接收搜索条件
            string userName = Request["name"];
            string userRemark = Request["remark"];
            int totalCount = 0;
            //构建搜索条件
            UserInfoSearch userInfoSearch = new UserInfoSearch
            {
                UserName = userName,
                UserRemark = userRemark,
                PageIndex = pageIndex,
                PageSize = pageSize,
                TotalCount = totalCount
            };
            short delFlag = (short)DeleteEnumType.Normarl;
            var userInfoList = UserInfoService.LoadSeachEntities(userInfoSearch, delFlag);
            var temp = from u in userInfoList
                       select new
                       {
                           u.ID,
                           u.UName,
                           u.UPwd,
                           u.Remark,
                           u.SubTime
                       };
            return Json(new { rows = temp, total = userInfoSearch.TotalCount }, JsonRequestBehavior.AllowGet);
        }

        #endregion
        #region 删除用户信息

        public ActionResult DeleteUserInfo()
        {
            string strId = Request["strId"];
            string[] strIds = strId.Split(',');
            List<int> list = new List<int>();
            foreach (var id in strIds)
            {
                list.Add(Convert.ToInt32(id));
            }
            if (UserInfoService.DeleteEntities(list))
            {
                return Content("ok");
            }
            else
            {
                return Content("no");
            }
        }
        #endregion
        #region 添加用户数据
        public ActionResult AddUserInfo(UserInfo userInfo)
        {
            userInfo.DelFlag = 0;
            userInfo.ModifienOn = DateTime.Now;
            userInfo.SubTime = DateTime.Now;
            UserInfoService.AddEntity(userInfo);
            return Content("ok");
        }

        #endregion
        #region 展示要修改的数据
        public ActionResult ShowEditInfo()
        {
            int id = int.Parse(Request["id"]);
            var userInfo = UserInfoService.LoadEntities(c => c.ID == id).FirstOrDefault();
            return Json(userInfo, JsonRequestBehavior.AllowGet);
        }

        #endregion
        #region 完成用户数据的更新
        public ActionResult EditUserInfo(UserInfo userInfo)
        {
            userInfo.ModifienOn = DateTime.Now;
            if (UserInfoService.EditEntity(userInfo))
            {
                return Content("ok");
            }
            else
            {
                return Content("no");
            }
        }
        #endregion
    }

}

FirstDemo.OA/FirstDemo.OA/Views/Home/HomePage.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>HomePage</title>
    <link href="~/Content/themes/default/easyui.css" rel="stylesheet" />
    <link href="~/Content/themes/icon.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/jquery.easyui.min.js"></script>
    <script src="~/Scripts/easyui-lang-zh_CN.js"></script>
    <script type="text/javascript">
        $(function () {
            bindClickEvent();
        });
        function bindClickEvent() {
            $(".detailLink").click(function () {
                var title = $(this).text();
                var url = $(this).attr("url");
                var isExt = $("#tt").tabs('exists', title);
                if (isExt) {
                    $("#tt").tabs('select', title);
                    return;
                }
                $("#tt").tabs('add', {
                    title: title,
                    content: showContent(url),
                    closable: true
                })
            });
        }
        function showContent(url) {
            var str = '<ifram src="' + url + '" width="100%" height="100%" frameborder="0"></iframe>';
            return str;
        }

    </script>
    <style type="text/css">
        .txt {
            font-size: 20px;
            font-weight: bold;
            color: blue;
            margin-top: 10px;
            margin-left: 100px;
            float: left;
        }
    </style>
</head>
<body class="easyui-layout">
    <div data-option="region:'north',border:false" style="height:85px;background:#B3DFDA;padding:10px;overflow:hidden;background-image:url(/Content/Images/bg3.png)">
        <img src="~/Content/Images/logo.jpg" style="float:left" />
        <span class="txt">OA办公系统</span>
    </div>
    <div data-option="region:'west',split:true,title:'West'" style="width:150px;padding:3px;">
        <div class="easy-accordion" style="width:auto;height:auto">
            <div title="用户管理" data-option="iconCls:'icon-ok'" style="overflow:auto;padding:5px;">
                <a href="javascript:void(0)" class="detailLink" url="/UserInfo/Index">用户管理</a>
            </div>
            <div title="角色管理" data-option="iconCls:'icon-help'" style="overflow:auto;padding:5px;">
                <a href="javascript:void(0)" class="detailLink" url="/RoleInfo/Index">角色管理</a>
            </div>
        </div>
    </div>
    <div data-option="region:'south',border:false" style="height:50px;background:#A9FACD;padding:10px;">south region</div>
    <div data-option="region:'center',title:'Center'">
        <div class="easy-tabs" style="width:700px;height:250px;" fit="true" id="tt">
            <iframe src="/UserInfo/Index" width="100%" height="100%" frameborder="0"></iframe>
        </div>
    </div>
</body>
</html>

FirstDemo.OA/FirstDemo.OA/Views/Login/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title>OA后台管理系统</title>
    <script type="text/javascript">
        if (window.parent.window != window) {
            window.top.location.href = "/Home/CheckLogin";
        }
    </script>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script type="text/javascript">
        function changeCheckCode() {
            $("#img").attr("src", $("#img").attr("src") + 1);
        }
        function afterLogin(data) {
            var serverData = data.split(":");
            if (serverData[0] == "ok") {
                window.location.href = '/Home/Index';
            } else {
                $("#errorMsg").css("display", "block");
                $("#errorMsg").text(serverData[1]);
                changeCheckCode();
            }
        }
    </script>
    <style type="text/css">
        * {
            padding: 0;
            margin: 0;
        }

        body {
            text-align: center;
            background: #4974A4;
        }

        #login {
            width: 740px;
            margin: 0 auto;
            font-size: 12px;
        }

        #loginlogo {
            width: 700px;
            height: 100px;
            overflow: hidden;
            background: url('/Content/Images/logo.jpg') no-repeat;
            margin-top: 50px;
        }

        #loginpancel {
            width: 729px;
            position: relative;
            height: 300px;
        }

        .panel-h {
            width: 729px;
            height: 20px;
            background: url('/Content/Images/login/panel-h.gif') no-repeat;
            position: absolute;
            top: 0px;
            left: 0px;
            z-index: 3;
        }

        .pancel-f {
            width: 729px;
            height: 13px;
            background: url('/Content/Images/login/panel-f.gif') no-repeat;
            position: absolute;
            top: 0px;
            left: 0px;
            z-index: 3;
        }

        .pancel-c {
            z-index: 2;
            background: url('/Content/Images/login/panel-c.gif') no-repeat;
            width: 729px;
            height: 300px;
        }

        .pancel-c-l {
            position: absolute;
            left: 60px;
            top: 40px;
        }

        .pancel-c-r {
            position: absolute;
            right: 20px;
            top: 50px;
            width: 222px;
            line-height: 200%;
            text-align: left;
        }

        .pancel-c-l h3 {
            color: #556A85;
            margin-bottom: 10px;
        }

        .pancel-c-l td {
            padding: 7px;
        }

        .login-text {
            height: 24px;
            left: 24px;
            border: 1px solid #e9e9e9;
            background: #f9f9f9;
        }

        .login-btn {
            width: 114px;
            height: 29px;
            color: #E9FFFF;
            line-height: 29px;
            background: url('/Content/Images/login/login-btn.gif') no-repeat;
            border: none;
            overflow: hidden;
            cursor: pointer; /*光标外观*/
        }

        #longincopyright {
            text-align: center;
            color: white;
            margin-top: 50px;
        }

        a {
            color: black;
        }

            a:hover {
                color: red;
                text-decoration: underline;
            }
    </style>
</head>
<body style="padding:10px;">
    <div id="login">
        <div id="loginlogo"></div>
        <div id="loginpancel">
            <div class="panel-h"></div>
            <div class="pancel-c">
                <div class="pancel-c-l">
                    @using (Ajax.BeginForm("UserLogin", "Login", new { }, new AjaxOptions { HttpMethod = "post", OnSuccess = "afterLogin", LoadingElementId = "div1" }, new { id = "loginForm" }))
                    {
                        <table cellpadding="0" cellspacing="0">
                            <tbody>
                                <tr>
                                    <td align="left" colspan="2"><h3>请使用OA管理系统账号登录</h3></td>
                                </tr>
                                <tr>
                                    <td align="left">账号：</td>
                                    <td align="left"><input type="text" name="LoginCode" id="LoginCode" class="login-text" /></td>
                                </tr>
                                <tr>
                                    <td align="left">密码：</td>
                                    <td align="left"><input type="password" name="LoginPwd" id="LoginPwd" class="login-text" value="123" /></td>"
                                </tr>
                                <tr>
                                    <td>验证码：</td>
                                    <td align="left"><input type="text" class="login-text" id="code" name="vCode" value="1" /></td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td>
                                        <img id="img" src="/Login/ShowValidateCode?id=1" style="float:left;height:24px;" />
                                        <div style="float:left;margin-left:5px;margin-top:10px;">
                                            <a href="javascript:void(0)" onclick="changeCheckCode(); return false;">看不清，换一张</a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td align="center" colspan="2">
                                        <input type="submit" id="btnLogin" value="登录" class="login-btn" /><span id="errorMsg" style="font-size:14px;color:red;display:none;"></span>
                                        <div id="div1" style="display:none;">正在登录，请稍后...</div>
                                    </td>

                                </tr>
                            </tbody>
                        </table>
                    }
                </div>
                <div class="pancel-c-r">
                    <p>
                        请从左侧输入登录账号和登录密码。
                    </p>
                    <p>
                        如果遇到系统问题，请联系网络管理员。
                    </p>
                    <p>
                        如果没有账号，请联系网络管理员。
                    </p>
                    <p>
                        ......
                    </p>
                </div>
            </div>
            <div class="pancel-f"></div>
        </div>
        <div id="longincopyright">
            Copyright ? 2018
        </div>
    </div>
</body>
</html>

FirstDemo.OA/FirstDemo.OA/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 应用程序</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("应用程序名称", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("主页", "Index", "Home")</li>
                    <li>@Html.ActionLink("关于", "About", "Home")</li>
                    <li>@Html.ActionLink("联系方式", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 应用程序</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

FirstDemo.OA/FirstDemo.OA/Views/UserInfo/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="~/Content/themes/default/easyui.css" rel="stylesheet" />
    <link href="~/Content/themes/icon.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/jquery.easyui.min.js"></script>
    <script src="~/Scripts/easyui-lang-zh_CN.js"></script>
    <script src="~/Scripts/datapattern.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script type="text/javascript">
        $(function () {
            $("#addDiv").css("display", "none");
            $("#editDiv").css("display", "none");
            //给搜索按钮添加一个单击事件
            $("#btnSeach").click(function () {
                //获取用户输入的搜索数据
                var par = {
                    name: $("#txtSeachName").val(),
                    remark: $("#txtSeachRemark").val()
                };
                //将获取的搜索的数据发送到服务端
                loadData(par);
            });
        });
        function loadData(pars) {
            $("#tt").datagrid({
                url: '/UserInfo/GetUserInfoList',
                title: '用户数据表格',
                width: 700,
                height: 400,
                fitColumns: true,//列自适应
                nowrap: false,
                idField: 'ID',
                loadMsg: '正在加载用户信息',
                pagination: true,//是否有分页
                singleSelect: false,//是否单行选择
                pageSize: 5,//页大小，一页有多少数据
                pageNumber: 1,//当前页，默认的
                pageList: [5, 10, 15],
                queryParams: pars,//往后台传递参数
                columns: [[
                    { field: 'ck', checkbox: true, align: 'left', width: 50 },
                    { field: 'ID', title: '编号', width: 80 },
                    { field: 'UName', title: '姓名', width: 120 },
                    { field: 'UPwd', title: '密码', width: 120 },
                    { field: 'Remark', title: '备注', width: 120 },
                    {
                        field: 'SubTime', title: '时间', width: 80, align: 'right',
                        formatter: function (value) {
                            return (eval(value.replace(/\/Date\((\d+)\)\//gi, "new Date($1)"))).pattern("yyyy-M-d");
                        }
                    },

                ]],
                toolbar: [{
                    id: 'btnDelete',
                    text: '删除',
                    iconCls: 'icon-remove',
                    handler: function () {
                        deleteInfo();
                    }
                },
                {
                    id: 'btnAdd',
                    text: '添加',
                    iconCls: 'icon-add',
                    handler: function () {
                        addInfo();
                    }
                },
                {
                    id: 'btnEidt',
                    text: '编辑',
                    iconCls: 'icon-edit',
                    handler: function () {
                        showEditInfo();
                    }
                }],
            });
        };
        //删除数据
        function deleteInfo() {
            var rows = $("#tt").datagrid("getSelections")//获取所选择的行
            if (!rows || rows.length == 0) {
                $.messager.alert("提醒", "请选择要删除的记录!!", "error");
                return;
            }
            $.messager.confirm("提示", "确定要删除吗？", function (r) {
                if (r) {
                    var rowsLength = rows.length;
                    var strId = "";
                    for (var i = 0; i < rowsLength; i++) {
                        strId = strId + rows[i].ID + ',';//1,2,3
                    }
                    //去掉最后一个逗号
                    strId = strId.substr(0, strId.length - 1);
                    $.post("/UserInfo/DeleteUserInfo", { "strId": strId }, function (data) {
                        if (data == "ok") {
                            $("#tt").datagrid("reload");//加载表格不会跳转到第一页
                            $("#tt").datagrid("clearSelections")//清除上次操作的历史记录
                        }
                        else {
                            $.messager.alert("提醒", "删除记录失败！！", "error");
                        }
                    })
                }
            })
        }
        //添加数据
        function addInfo() {
            $("#addDiv").css("display", "block");
            $("#addDiv").dialog({
                title: "添加用户数据",
                width: 300,
                height: 200,
                collapsible: true,
                maxmizable: true,
                resizable: true,
                modal: true,
                buttons: [{
                    text: "OK",
                    iconCls: 'icon-ok',
                    handler: function () {
                        //表达效验
                        validateInfo($("#addForm"));
                        $("#addForm").submit();//提交表单
                    }
                }, {
                    text: "Cancel",
                    handler: function () {
                        $("#addDiv").dialog("close");
                    }
                }]
            });
        }
        //完成添加后调用
        function afterAdd(data) {
            if (data == "ok") {
                $("#addDiv").dialog("close");
                $("#tt").datagrid("reload");//加载表格不会跳转到第一页
                $("#addForm input").val("");
            }
        }
        //表单效验
        function validateInfo(control) {
            control.validate({//表示对哪个表单进行效验，获取form标签的id属性的值
                rules: {//表示验证规则
                    UName: "required",//表示对哪个表单元进行效验，要写具体的表单元素的name属性的值
                    Remark: {
                        required: true
                    },
                    UPwd: {
                        required: true,
                        minlength: 5
                    },
                    Sort: {
                        required: true
                    }
                },
                messages: {
                    UName: "请输入用户名",
                    Remark: {
                        required: "请输入备注"
                    },
                    UPwd: {
                        required: "请输入密码",
                        minlength: "密码不能小于{0}个字符"
                    },
                    Sort: {
                        required: "请输入排序"
                    }
                }
            })
        }
        //展示一下要修改的数据
        function showEditInfo() {
            //判断一下用户是否选择了要修改的数据
            var row = $("#tt").datagrid("getSelections");//获取选择的行
            if (row.length != 1) {
                $.messager.alert("提示", "请先选择要修改的数据", "error");
                return;
            }
            //将要修改的数据查询出来，显示到文本框中
            var id = row[0].ID;
            $.post("/UserInfo/ShowEditInfo", { "id": id }, function (data) {
                $("#txtId").val(data.ID);
                $("#txtSubTime").val(ChangeDateFormat(data.SubTime));
                $("#txtDelFlag").val(data.DelFlag);
                $("#txtUName").val(data.UName);
                $("#txtUPwd").val(data.UPwd);
                $("#txtRemark").val(data.Remark);
                $("#txtSort").val(data.Sort);
            });
            $("#editDiv").css("display", "block");
            $("#editDiv").dialog({
                title: "编辑用户数据",
                width: 400,
                height: 200,
                collapsible: true,
                maxmizable: true,
                resizable: true,
                modal: true,
                buttons: [{
                    text: 'OK',
                    iconCls: 'icon-ok',
                    handler: function () {
                        //表单验证
                        validateInfo($("#editForm"));
                        $("#editForm").submit();//提交表单
                    }
                }, {
                    text: 'Cancel',
                    handler: function () {
                        $("#editDiv").dialog("close");
                    }
                }]
            });
        }
        //更新之后调用该方法
        function afterEdit(data) {
            if (data == 'ok') {
                $("#editDiv").dialog('close');
                $("#tt").datagrid("reload");//加载表格不会跳转到第一页
            } else {
                $.messager.alert("提示", "修改数据失败", "error");
            }
        }

        //将序列化成json格式的日期（毫秒数）转换成日期形式
        function ChangeDateFormat(cellval) {
            var date = new Date(parseInt(cellval.replace("/Date(", "").replace(")/", ""), 10));
            var month = date.getMonth() + 1 < 10 ? "0" + (date.getMonth() + 1) : date.getMonth() + 1;
            var currentDate = date.getDate() < 10 ? "0" + date.getDate() : date.getDate();
            return date.getFullYear() + "-" + month + "-" + currentDate;
        }
    </script>
</head>
<body>
    <div>
        用户名：<input type="text" id="txtSeachName" />&nbsp;&nbsp;备注：<input type="text" id="txtSeachRemark" /><a href="#" class="easyui-linkbutton" data-options="iconCls:'icon-seach'" style="width:80px;" id="btnSeach">Seach</a>
        <table id="tt" style="width:700px;" title="标题，可以使用代码初始化，也可以使用这种属性的方式" icccls="icon-edit"></table>
    </div>
    <!------添加数据------->
    <div id="addDiv">
        @using (Ajax.BeginForm("AddUserInfo", "UserInfo", new { }, new AjaxOptions() { HttpMethod = "post", OnSuccess = "afterAdd" }, new { id = "addForm" }))
        {
            <table>
                <tr><td>用户名</td><td><input type="text" name="UName" /></td></tr>
                <tr><td>密码</td><td><input type="text" name="UPwd" /></td></tr>
                <tr><td>备注</td><td><input type="text" name="Remark" /></td></tr>
                <tr><td>排序</td><td><input type="text" name="Sort" /></td></tr>
            </table>
        }
    </div>

    <!----修改数据---->
    <div id="editDiv">
        @using (Ajax.BeginForm("EditUserInfo", "UserInfo", new { }, new AjaxOptions() { HttpMethod = "post", OnSuccess = "afterEdit" }, new { id = "editForm" }))
        {
            <input type="hidden" name="ID" id="txtId" />
            <input type="hidden" name="SubTime" id="txtSubTime" />
            <input type="hidden" name="DelFlag" id="txtDelFlag" />
            <table>
                <tr><td>用户名</td><td><input type="text" name="UName" id="txtUName" /></td></tr>
                <tr><td>密码</td><td><input type="text" name="UPwd" id="txtUPwd" /></td></tr>
                <tr><td>备注</td><td><input type="text" name="Remark" id="txtRemark" /></td></tr>
                <tr><td>排序</td><td><input type="text" name="Sort" id="txtSort" /></td></tr>
            </table>
        }
    </div>
</body>

</html>